#
# Copyright (c) 2017 Richard Delaplace
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'spec_helper'

packages = [
  'ntp'
]
dependencies = [
  'cowsay',
  'toilet',
  'fortune-mod'
]

describe 'Packages' do
  packages.each do |pkg|
    describe package(pkg) do
      it { should be_installed }
    end
  end
  dependencies.each do |pkg|
    describe package(pkg) do
      it { should be_installed }
    end
  end
end

describe 'Files' do
  describe file('/tmp/config') do
    it { should exist }
    it { should be_owned_by 'root' }
    it { should be_grouped_into 'root' }
    it { should be_mode 700 }
    its(:content) do
      should contain \
        '### Files generated by Puppet, please do not edit manually'
    end
  end
  describe file('/tmp/sysconfig') do
    it { should exist }
    it { should be_owned_by 'root' }
    it { should be_grouped_into 'root' }
    it { should be_mode 644 }
    its(:content) do
      should contain \
        '### Files generated by Puppet, please do not edit manually'
    end
  end
end
